/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteCodeRouteImport } from './routes/$inviteCode'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomerServiceRouteImport } from './routes/customer-service'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessageRouteImport } from './routes/message'
import { Route as MineRouteImport } from './routes/mine'
import { Route as OrderRouteImport } from './routes/order'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PinRouteImport } from './routes/pin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as TaskRouteImport } from './routes/task'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as UpiRouteImport } from './routes/upi'
import { Route as UsdtDepositRouteImport } from './routes/usdt-deposit'
import { Route as ReferralCodeRegisterRouteImport } from './routes/$referralCode.register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminCustomerServiceRouteImport } from './routes/admin.customer-service'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as AdminGatewaysRouteImport } from './routes/admin.gateways'
import { Route as AdminSellOrdersRouteImport } from './routes/admin.sell-orders'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AgentDashboardRouteImport } from './routes/agent.dashboard'
import { Route as AgentLoginRouteImport } from './routes/agent.login'
import { Route as ApiPublicSendOtpRouteImport } from './routes/api/public/send-otp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/$inviteCode',
  path: '/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceRoute = CustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRoute = MessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRouteImport,
} as any)
const MineRoute = MineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskRoute = TaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const UpiRoute = UpiRouteImport.update({
  id: '/upi',
  path: '/upi',
  getParentRoute: () => rootRouteImport,
} as any)
const UsdtDepositRoute = UsdtDepositRouteImport.update({
  id: '/usdt-deposit',
  path: '/usdt-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralCodeRegisterRoute = ReferralCodeRegisterRouteImport.update({
  id: '/$referralCode/register',
  path: '/$referralCode/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerServiceRoute = AdminCustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGatewaysRoute = AdminGatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellOrdersRoute = AdminSellOrdersRouteImport.update({
  id: '/sell-orders',
  path: '/sell-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent/dashboard',
  path: '/agent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/agent/login',
  path: '/agent/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendOtpRoute = ApiPublicSendOtpRouteImport.update({
  id: '/api/public/send-otp',
  path: '/api/public/send-otp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$inviteCode': typeof InviteCodeRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer-service': typeof CustomerServiceRoute
  '/deposit': typeof DepositRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/message': typeof MessageRoute
  '/mine': typeof MineRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/pin': typeof PinRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/score': typeof ScoreRoute
  '/statistics': typeof StatisticsRoute
  '/task': typeof TaskRoute
  '/team': typeof TeamRoute
  '/tutorial': typeof TutorialRoute
  '/upi': typeof UpiRoute
  '/usdt-deposit': typeof UsdtDepositRoute
  '/$referralCode/register': typeof ReferralCodeRegisterRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/customer-service': typeof AdminCustomerServiceRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/sell-orders': typeof AdminSellOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/login': typeof AgentLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/send-otp': typeof ApiPublicSendOtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$inviteCode': typeof InviteCodeRoute
  '/customer-service': typeof CustomerServiceRoute
  '/deposit': typeof DepositRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/message': typeof MessageRoute
  '/mine': typeof MineRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/pin': typeof PinRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/score': typeof ScoreRoute
  '/statistics': typeof StatisticsRoute
  '/task': typeof TaskRoute
  '/team': typeof TeamRoute
  '/tutorial': typeof TutorialRoute
  '/upi': typeof UpiRoute
  '/usdt-deposit': typeof UsdtDepositRoute
  '/$referralCode/register': typeof ReferralCodeRegisterRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/customer-service': typeof AdminCustomerServiceRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/sell-orders': typeof AdminSellOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/login': typeof AgentLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/send-otp': typeof ApiPublicSendOtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$inviteCode': typeof InviteCodeRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer-service': typeof CustomerServiceRoute
  '/deposit': typeof DepositRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/message': typeof MessageRoute
  '/mine': typeof MineRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/pin': typeof PinRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/score': typeof ScoreRoute
  '/statistics': typeof StatisticsRoute
  '/task': typeof TaskRoute
  '/team': typeof TeamRoute
  '/tutorial': typeof TutorialRoute
  '/upi': typeof UpiRoute
  '/usdt-deposit': typeof UsdtDepositRoute
  '/$referralCode/register': typeof ReferralCodeRegisterRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/customer-service': typeof AdminCustomerServiceRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/sell-orders': typeof AdminSellOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/login': typeof AgentLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/send-otp': typeof ApiPublicSendOtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$inviteCode'
    | '/admin'
    | '/customer-service'
    | '/deposit'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/message'
    | '/mine'
    | '/order'
    | '/orders'
    | '/payment'
    | '/pin'
    | '/register'
    | '/reset-password'
    | '/score'
    | '/statistics'
    | '/task'
    | '/team'
    | '/tutorial'
    | '/upi'
    | '/usdt-deposit'
    | '/$referralCode/register'
    | '/admin/agents'
    | '/admin/banners'
    | '/admin/customer-service'
    | '/admin/deposits'
    | '/admin/gateways'
    | '/admin/sell-orders'
    | '/admin/settings'
    | '/admin/users'
    | '/agent/dashboard'
    | '/agent/login'
    | '/admin/'
    | '/api/public/send-otp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$inviteCode'
    | '/customer-service'
    | '/deposit'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/message'
    | '/mine'
    | '/order'
    | '/orders'
    | '/payment'
    | '/pin'
    | '/register'
    | '/reset-password'
    | '/score'
    | '/statistics'
    | '/task'
    | '/team'
    | '/tutorial'
    | '/upi'
    | '/usdt-deposit'
    | '/$referralCode/register'
    | '/admin/agents'
    | '/admin/banners'
    | '/admin/customer-service'
    | '/admin/deposits'
    | '/admin/gateways'
    | '/admin/sell-orders'
    | '/admin/settings'
    | '/admin/users'
    | '/agent/dashboard'
    | '/agent/login'
    | '/admin'
    | '/api/public/send-otp'
  id:
    | '__root__'
    | '/'
    | '/$inviteCode'
    | '/admin'
    | '/customer-service'
    | '/deposit'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/message'
    | '/mine'
    | '/order'
    | '/orders'
    | '/payment'
    | '/pin'
    | '/register'
    | '/reset-password'
    | '/score'
    | '/statistics'
    | '/task'
    | '/team'
    | '/tutorial'
    | '/upi'
    | '/usdt-deposit'
    | '/$referralCode/register'
    | '/admin/agents'
    | '/admin/banners'
    | '/admin/customer-service'
    | '/admin/deposits'
    | '/admin/gateways'
    | '/admin/sell-orders'
    | '/admin/settings'
    | '/admin/users'
    | '/agent/dashboard'
    | '/agent/login'
    | '/admin/'
    | '/api/public/send-otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteCodeRoute: typeof InviteCodeRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerServiceRoute: typeof CustomerServiceRoute
  DepositRoute: typeof DepositRoute
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessageRoute: typeof MessageRoute
  MineRoute: typeof MineRoute
  OrderRoute: typeof OrderRoute
  OrdersRoute: typeof OrdersRoute
  PaymentRoute: typeof PaymentRoute
  PinRoute: typeof PinRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScoreRoute: typeof ScoreRoute
  StatisticsRoute: typeof StatisticsRoute
  TaskRoute: typeof TaskRoute
  TeamRoute: typeof TeamRoute
  TutorialRoute: typeof TutorialRoute
  UpiRoute: typeof UpiRoute
  UsdtDepositRoute: typeof UsdtDepositRoute
  ReferralCodeRegisterRoute: typeof ReferralCodeRegisterRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  AgentLoginRoute: typeof AgentLoginRoute
  ApiPublicSendOtpRoute: typeof ApiPublicSendOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$inviteCode': {
      id: '/$inviteCode'
      path: '/$inviteCode'
      fullPath: '/$inviteCode'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service': {
      id: '/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof CustomerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mine': {
      id: '/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof MineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task': {
      id: '/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upi': {
      id: '/upi'
      path: '/upi'
      fullPath: '/upi'
      preLoaderRoute: typeof UpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usdt-deposit': {
      id: '/usdt-deposit'
      path: '/usdt-deposit'
      fullPath: '/usdt-deposit'
      preLoaderRoute: typeof UsdtDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$referralCode/register': {
      id: '/$referralCode/register'
      path: '/$referralCode/register'
      fullPath: '/$referralCode/register'
      preLoaderRoute: typeof ReferralCodeRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer-service': {
      id: '/admin/customer-service'
      path: '/customer-service'
      fullPath: '/admin/customer-service'
      preLoaderRoute: typeof AdminCustomerServiceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gateways': {
      id: '/admin/gateways'
      path: '/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AdminGatewaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sell-orders': {
      id: '/admin/sell-orders'
      path: '/sell-orders'
      fullPath: '/admin/sell-orders'
      preLoaderRoute: typeof AdminSellOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agent/dashboard': {
      id: '/agent/dashboard'
      path: '/agent/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/agent/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-otp': {
      id: '/api/public/send-otp'
      path: '/api/public/send-otp'
      fullPath: '/api/public/send-otp'
      preLoaderRoute: typeof ApiPublicSendOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCustomerServiceRoute: typeof AdminCustomerServiceRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminGatewaysRoute: typeof AdminGatewaysRoute
  AdminSellOrdersRoute: typeof AdminSellOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCustomerServiceRoute: AdminCustomerServiceRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminGatewaysRoute: AdminGatewaysRoute,
  AdminSellOrdersRoute: AdminSellOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteCodeRoute: InviteCodeRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerServiceRoute: CustomerServiceRoute,
  DepositRoute: DepositRoute,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessageRoute: MessageRoute,
  MineRoute: MineRoute,
  OrderRoute: OrderRoute,
  OrdersRoute: OrdersRoute,
  PaymentRoute: PaymentRoute,
  PinRoute: PinRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScoreRoute: ScoreRoute,
  StatisticsRoute: StatisticsRoute,
  TaskRoute: TaskRoute,
  TeamRoute: TeamRoute,
  TutorialRoute: TutorialRoute,
  UpiRoute: UpiRoute,
  UsdtDepositRoute: UsdtDepositRoute,
  ReferralCodeRegisterRoute: ReferralCodeRegisterRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  AgentLoginRoute: AgentLoginRoute,
  ApiPublicSendOtpRoute: ApiPublicSendOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
